GET https://www.gadzconnect.com/api/admin/allAdmins HTTP/1.1

###

GET https://www.gadzconnect.com/api/user/view HTTP/1.1

###

POST https://www.gadzconnect.com/api/admin HTTP/1.1
content-type: application/json

{
    "email": "vaughn@retroluxe.com",
    "password": "test123",
    "description": "developer",
    "admin": "true",
    "developer": "false",
    "archived": "false",
    "contractor": "true",
    "company": "false"
}