GET http://localhost:3001/api/user/allUsers HTTP/1.1

###

GET http://localhost:3001/api/user/allUsers HTTP/1.1

###

POST http://localhost:3001/api/user HTTP/1.1
content-type: application/json

{
    "email": "hbjbj@bhjbjbjbjb.com",
    "password": "test123",
    "description": "developer",
    "admin": "true",
    "developer": "false",
    "archived": "false",
    "contractor": "true",
    "company": "false"
}