
//**Getting info from the your localhost Database.**//
// Funny how this works. 
GET http://localhost:3001/api/user/allUsers HTTP/1.1

###

//**Getting info from the production Database.**//
GET https://www.GADZConnect.com/api/user/allUsers HTTP/1.1

###

//**Sending info to the production Database.**//
POST https://www.GADZConnect.com/api/user HTTP/1.1
content-type: application/json

{
    "email": "vincent@kendrick.com",
    "password": "test123",
    "description": "developer",
    "admin": "true",
    "developer": "true",
    "archived": "false",
    "contractor": "true",
    "company": "false"
}